[workspace]
resolver = "2"
members = [
	"fontique"
]

[workspace.package]
edition = "2021"
# Keep in sync with RUST_MIN_VER in .github/workflows/ci.yml and with the relevant README.md files.
rust-version = "1.70"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/linebender/parley"

[package]
name = "parley"
version = "0.1.0"
description = "Parley provides an API for implementing rich text layout."
keywords = ["text", "layout"]
categories = ["gui", "graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
exclude = ["/.github/", "/doc/", ".gitignore"]

[workspace.lints]
clippy.doc_markdown = "warn"
clippy.semicolon_if_nothing_returned = "warn"
clippy.trivially_copy_pass_by_ref = "warn"

[lints]
workspace = true

[features]
default = ["system"]
std = ["fontique/std", "skrifa/std", "peniko/std"]
libm = ["fontique/libm", "skrifa/libm", "peniko/libm"]
# Enables support for system font backends
system = ["std", "fontique/system"]

[dependencies]
swash = "0.1.15"
skrifa = { workspace = true }
peniko = { workspace = true }
fontique = { workspace = true }

[dev-dependencies]
tiny-skia = "0.11.4"

[workspace.dependencies]
fontique = { version = "0.1.0", default-features = false, path = "fontique" }
skrifa = { version = "0.19.1", default-features = false }
peniko = { version = "0.1.0", default-features = false }
